### ISSUE TITLE
Error when using twice

### ISSUE THREAD

**Issue by rleibman** [postmanlabs/npm-cli-login#10]
In a very inconsistent way, I get errors when trying ot use npm-cli-login twice. The first time it works ok, the second time I get 

`info attempt registry request try #1 at 18:35:39
http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:gluenetworks
http 400 https://registry.npmjs.org/-/user/org.couchdb.user:gluenetworks
/usr/local/lib/node_modules/npm-cli-login/lib/index.js:11
            throw new Error(err);
                  ^
Error: Error: Unknown error while authenticating : -/user/org.couchdb.user:gluenetworks
    at /usr/local/lib/node_modules/npm-cli-login/lib/index.js:11:19
    at /usr/local/lib/node_modules/npm-cli-login/lib/login.js:58:24
    at /usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/lib/adduser.js:125:14
    at /usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/lib/adduser.js:73:16
    at f (/usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/node_modules/once/once.js:17:25)
    at /usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/lib/request.js:89:10
    at f (/usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/node_modules/once/once.js:17:25)
    at RegClient.<anonymous> (/usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/lib/request.js:259:12)
    at Request._callback (/usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/lib/request.js:172:14)
    at Request.self.callback (/usr/local/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/node_modules/request/request.js:199:22)`

Incidentally, this also breaks the normal "npm login" mechanism, and I have to remove ~/.nmp* before I can log in again.

**Comment by madebysid** [comment]
@rleibman The module is a wrapper around [npm-registry-client](https://github.com/npm/npm-registry-client). From the logs, it looks like something went wrong internally in their module. I will try to debug this, and hopefully stop it from corrupting your `npmrc` file. Thanks for letting me know. Will keep you posted.
