### ISSUE TITLE
Does not work on windows anymore

### ISSUE THREAD

**Issue by webmutation** [postmanlabs/npm-cli-login#22]
Try to run it on a Windows Bamboo agent and the config-path does not work anymore... 

error	20-Feb-2018 09:28:19	TypeError: Path must be a string. Received undefined
error	20-Feb-2018 09:28:19	    at assertPath (path.js:7:11)
error	20-Feb-2018 09:28:19	    at Object.join (path.js:468:7)
error	20-Feb-2018 09:28:19	    at Object.processArguments (E:\bamboo\remoteagent\xml-data\build-dir\UXATEC-CSDR-JOB1\node_modules\npm-cli-login\lib\login.js:34:56)
error	20-Feb-2018 09:28:19	    at module.exports (E:\bamboo\remoteagent\xml-data\build-dir\UXATEC-CSDR-JOB1\node_modules\npm-cli-login\lib\index.js:4:25)
error	20-Feb-2018 09:28:19	    at login (E:\bamboo\remoteagent\xml-data\build-dir\UXATEC-CSDR-JOB1\node_modules\npm-cli-login\bin\npm-cli-login.js:30:19)
error	20-Feb-2018 09:28:19	    at Object.<anonymous> (E:\bamboo\remoteagent\xml-data\build-dir\UXATEC-CSDR-JOB1\node_modules\npm-cli-login\bin\npm-cli-login.js:33:1)
error	20-Feb-2018 09:28:19	    at Module._compile (module.js:570:32)
error	20-Feb-2018 09:28:19	    at Object.Module._extensions..js (module.js:579:10)
error	20-Feb-2018 09:28:19	    at Module.load (module.js:487:32)
error	20-Feb-2018 09:28:19	    at tryModuleLoad (module.js:446:12)

When setting the path to  --config-path "./.npmrc"  trying to connect to the repository behind a proxy fails with 

error	21-Feb-2018 16:37:38	info attempt registry request try #1 at 4:37:38 PM
error	21-Feb-2018 16:37:38	http request PUT https://**********com/repository/npm-all/-/user/org.couchdb.user:*******as
error	21-Feb-2018 16:37:40	info retry will retry, error on last attempt: Error: connect ECONNREFUSED ***.***.**.***:443

**Comment by Berezhnyk** [comment]
I have the same problem

**Comment by yammerade** [comment]
I have this problem as well.

**Comment by kittaakos** [comment]
As a workaround, you can do
```js
if (!process.env.HOME) {
  process.env.HOME = require('os').homedir();
}
```
before calling
```js
require('npm-cli-login')('name', 'password');
```
on Windows.

**Comment by yammerade** [comment]
@kittaakos this works for me, thanks

**Comment by rmccarthy-ellevation** [comment]
Can we have a fix implemented for this, still not fixed and annoying to use.
