### ISSUE TITLE
Cannot install package due to incident on snyk servers

### ISSUE THREAD

**Issue by claudinoac** [postmanlabs/npm-cli-login#83]
I use this package as a part of CI/CD of a bunch of projects and recently all of them started to fail because of snyk dependecy that cannot be installed, and I believe that it is related to the incident they are going through right now -> https://status.snyk.io/incidents/0ywz8h22kwzm

It's not the first time something like that happens:
* https://github.com/postmanlabs/npm-cli-login/issues/80
* https://github.com/postmanlabs/npm-cli-login/issues/45
* https://github.com/postmanlabs/npm-cli-login/issues/39

I looked the code and I haven't seen any reason for snyk to be a direct dependency of this project and imported in all other projects that uses this package. 

This is the stack-trace I'm seeing right now

```
/home/travis/.nvm/versions/node/v14.21.2/bin/npm-cli-login -> /home/travis/.nvm/versions/node/v14.21.2/lib/node_modules/npm-cli-login/bin/npm-cli-login.js

> snyk@1.1102.0 postinstall /home/travis/.nvm/versions/node/v14.21.2/lib/node_modules/npm-cli-login/node_modules/snyk

> node dist/bootstrap.js exec

Downloading from 'https://static.snyk.io/cli/v1.1102.0/snyk-linux' to '/home/travis/.nvm/versions/node/v14.21.2/lib/node_modules/npm-cli-login/node_modules/snyk/dist/snyk-linux'

Error: Shasum comparison failed!

Shasums:

- actual:   c620fa1698e9ddefd92d2f79f0bee8169271077b6b24a75f40bba513586891f6

- expected: 53e32de971fe2a673e6a0e506c5399bac44f19e6736e281226e856047bb35e07

    at WriteStream.<anonymous> (/home/travis/.nvm/versions/node/v14.21.2/lib/node_modules/npm-cli-login/node_modules/snyk/dist/common.js:203:39)

    at WriteStream.emit (events.js:412:35)

    at WriteStream.emit (domain.js:475:12)

    at finish (internal/streams/writable.js:657:10)

    at finishMaybe (internal/streams/writable.js:644:9)

    at internal/streams/writable.js:617:7

    at WriteStream._final (internal/fs/streams.js:315:3)

    at callFinal (internal/streams/writable.js:610:10)

    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by nicolas2mey** [comment]
impacted here too

shouldn't snyk to be considered as dev dependency ?

**Comment by jg75** [comment]
Sam error here on 1.1103.0 using AWS CodeBuild


Downloading from 'https://static.snyk.io/cli/v1.1103.0/snyk-linux' to '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/snyk-linux'
--
74 | events.js:377
75 | throw er; // Unhandled 'error' event
76 | ^
77 |  
78 | Error: EACCES: permission denied, open '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676317675289'
79 | Emitted 'error' event on WriteStream instance at:
80 | at internal/fs/streams.js:335:14
81 | at FSReqCallback.oncomplete (fs.js:180:23) {
82 | errno: -13,
83 | code: 'EACCES',
84 | syscall: 'open',
85 | path: '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676317675289'
86 | }
87 | npm ERR! code ELIFECYCLE
88 | npm ERR! errno 1
89 | npm ERR! snyk@1.1103.0 postinstall: `node dist/bootstrap.js exec`
90 | npm ERR! Exit status 1
91 | npm ERR!
92 | npm ERR! Failed at the snyk@1.1103.0 postinstall script.
93 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
94 |  
95 | npm ERR! A complete log of this run can be found in:
96 | npm ERR!     /root/.npm/_logs/2023-02-13T19_47_55_588Z-debug.log

**Comment by claudinoac** [comment]
For those looking for an alternative to this package while this issue is not fixed (or permanently), there's this fork that works pretty well and does not depend on snyk. https://github.com/KenanY/npm-cli-login/

**Comment by animyrch** [comment]
We had this same issue as well. But since a few minutes ago. it has disappeared. Pipeline installs are working again

**Comment by jg75** [comment]
Seeing the same thing with snyk 1.1103.0

/usr/local/bin/npm-cli-login -> /usr/local/lib/node_modules/npm-cli-login/bin/npm-cli-login.js
--
69 |  
70 | > snyk@1.1103.0 postinstall /usr/local/lib/node_modules/npm-cli-login/node_modules/snyk
71 | > node dist/bootstrap.js exec
72 |  
73 | Downloading from 'https://static.snyk.io/cli/v1.1103.0/snyk-linux' to '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/snyk-linux'
74 | events.js:377
75 | throw er; // Unhandled 'error' event
76 | ^
77 |  
78 | Error: EACCES: permission denied, open '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676327944111'
79 | Emitted 'error' event on WriteStream instance at:
80 | at internal/fs/streams.js:335:14
81 | at FSReqCallback.oncomplete (fs.js:180:23) {
82 | errno: -13,
83 | code: 'EACCES',
84 | syscall: 'open',
85 | path: '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676327944111'
86 | }
87 | npm ERR! code ELIFECYCLE
88 | npm ERR! errno 1
89 | npm ERR! snyk@1.1103.0 postinstall: `node dist/bootstrap.js exec`
90 | npm ERR! Exit status 1
91 | npm ERR!
92 | npm ERR! Failed at the snyk@1.1103.0 postinstall script.
93 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
94 |  
95 | npm ERR! A complete log of this run can be found in:
96 | npm ERR!     /root/.npm/_logs/2023-02-13T22_39_04_503Z-debug.log
97 |  
98 | [Container] 2023/02/13 22:39:04 Command did not exit successfully npm install -g npm-cli-login exit status 1

**Comment by zhangmo8** [comment]
The same problem as me.

**Comment by xumeng** [comment]
Same error, Anyone is dealing this error?

**Comment by xumeng** [comment]
Here is update news... https://github.com/snyk/cli/issues/4406#issuecomment-1429348217
<img width="828" alt="image" src="https://user-images.githubusercontent.com/2187660/218689864-7195fc33-e849-49d0-b4e7-d4fa1cd61759.png">

**Comment by nm24781-cyber** [comment]
> Here is update news... [snyk/cli#4406 (comment)](https://github.com/snyk/cli/issues/4406#issuecomment-1429348217) <img alt="image" width="828" src="https://user-images.githubusercontent.com/2187660/218689864-7195fc33-e849-49d0-b4e7-d4fa1cd61759.png">

Thanks for quick fix

**Comment by zhangmo8** [comment]
After I upgraded my node version, it took effect

**Comment by rajharsh1997** [comment]
> For those looking for an alternative to this package while this issue is not fixed (or permanently), there's this fork that works pretty well and does not depend on snyk. `https://github.com/KenanY/npm-cli-login/`

Thanks for the quickfix fork link. Are you able to run it? I was facing another issue while using this fork -
`npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/@kenan/npm-cli-login/bin/npm-cli-login.js
npm ERR! dest /home/ubuntu/actions-runner/_work/_tool/node/12.22.5/x64/bin/npm-cli-login
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/@kenan/npm-cli-login/bin/npm-cli-login.js' -> '/home/ubuntu/actions-runner/_work/_tool/node/12.22.5/x64/bin/npm-cli-login'
npm ERR! File exists: /home/ubuntu/actions-runner/_work/_tool/node/12.22.5/x[64](https://github.com/tandfgroup/oadashboard-web/actions/runs/4182483472/jobs/7245626781#step:10:65)/bin/npm-cli-login
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.`
